language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - ./bin/install.sh
  -  mysql -e 'CREATE DATABASE php_gyazo_test;'
  - cp ./config/example.php ./config/development.php

script: phpunit --coverage-text
